### ISSUE TITLE
Using openssh in cmd / git bash

### ISSUE THREAD

**Issue by Centril** [dlech/KeeAgent#114]
I have 2 github users, and thus 2 ssh keys in KeeAgent/Pass.
Using plink works, but github uses the wrong key first and then rejects that one and then doesn't go on to the next ones... The only option for me right now is to select the key I want via the dialog.

I really want to be able to use OpenSSH in cmd / git bash since it gives me the option of having a `~/.ssh/config` file like so:
```
host github.com
 HostName github.com
 IdentityFile ~/.ssh/id_github_user1_keepass_rsa
 User git

host github.com-user2
 HostName github.com
 IdentityFile ~/.ssh/id_github_user2_keepass_rsa
 User git
```
Is it either possible to make KeeAgent work with OpenSSH in cmd / git bash or make this work with plink via some batch/shell script that filters out some keys, or any other method I'm overlooking?

Is this related to "URL Overrides"? This info was quite vague on what it actually does: http://lechnology.com/software/keeagent/usage/tips-and-tricks/

**Comment by dlech** [comment]
You should be able to do what you want here.

First, to use OpenSSH in git bash, you need to setup a [MSYS socket file](http://lechnology.com/software/keeagent/usage/tips-and-tricks/#cygwin-and-msys).

Then if you want to store the private keys in you KeePass database, there is a bit of a problem here since it doesn't actually tell you where it is saving the file to. You can find out by setting up a URL Override and then use that path in your `~/.ssh/config` file.

Another option would be to store your private key on disk and tell the entry in KeePass to use an "External File" instead of "Attachment".

**Comment by Centril** [comment]
Never mind this issue, I tried making a socket at: `~/.ssh/cygwinsocket` via Keepass2 > Options > KeeAgent > "Create Cygwin compatible socket file..." and directed SSH_AUTH_SOCK in to that and made it permanent.

Didn't have to touch URL Override at all.

Do you know if it is possible to make this a bit more intelligent, like... create a rule that says: "if we have a git remote url like: git@github.com:{user}/{repo}.git, then if {user} == XYZ, use this key, otherwise use something else...

How does the call chain look like...? When is KeeAgent involved, before or after GIT_SSH is invoked?
Can I use custom fields in KeeAgent/Pass for this scripting somehow?

**Comment by dlech** [comment]
The call chain is like this:

1. User runs command that invokes ssh (so this is while `GIT_SSH` is being invoked, not before or after).
2. If a key file was not specified either via the command line or `~/.ssh/config`, ssh sends a request to get a list of all keys, otherwise skip to 6.
3. If the option in KeeAgent is selected, a dialog prompting the user to select a key, otherwise all loaded keys are returned.
4. The ssh program sends the public key hash to the server to see if it has a match.
5. The server sends back the matching key or an error. If there is an error, ssh skips the next steps and tries a different authentication mechanism (like interactive password).
6. The ssh program sends a request to the agent to sign some data with the matching key (or the key specified in the key file if there was one).
7. The agent signs the request and sends the signature back to the ssh program.
8. The ssh program sends the signature to the server for verification. If there is an error, ssh tries a different method of authentication.
9. If all went well, you can now communicate to the server via ssh.

As for the possibility of making this more intelligent, this is being discussed in #90. There isn't a way to do exactly what you are suggesting now that I know of. The best option right now is to specify the key file when invoking ssh.

**Comment by Centril** [comment]
OK, thanks for clarifying, closing the issue for now =)
