### ISSUE TITLE
Make ssh-agent compatible with powershell

### ISSUE THREAD

**Issue by blaggacao** [dlech/KeeAgent#155]
There seems to be two options:

native ssh on windows, yet it is still very unstable and I didn't have much luck with it's usage so far.
https://github.com/PowerShell/Win32-OpenSSH

Or use those Powershellbindungs:
http://markembling.info/2009/09/ssh-agent-in-powershell

Kind regards

**Comment by blaggacao** [comment]
Here are some updated instructions on ssh-agent. I will try them...
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by dlech** [comment]
`ssh-agent` works in powershell with [posh-git](http://dahlbyk.github.io/posh-git/).

**Comment by dlech** [comment]
Not sure how to integrate it with KeeAgent though.

**Comment by coldacid** [comment]
If all else fails, saving the key to a temporary file, calling `ssh-add` on the file, and passing in the password on the process' stdin stream should do the trick. That said, I'm fairly certain that Win32-OpenSSH's ssh-agent service uses the same agent protocol as the standard version, even if over a named pipe instead of Unix domain sockets.

**Comment by dlech** [comment]
Closing in favor of #207
