### ISSUE TITLE
Too many authentication failures for user

### ISSUE THREAD

**Issue by poblabs** [dlech/KeeAgent#200]
Hi there, really enjoy KeeAgent, thank you for it. Been using it for a long time and I'm having a new issue. 

KeePass 2.36
KeeAgent 0.8.1

I have only 6 keys loaded and the SSH hosts which use key auth are working fine. Any other host that is using password auth gives me "Too many authentication failures for user" error in PuTTY. If I close KeeAgent then I can log into those password auth hosts. 

I don't see anything common with them (can't say they have the same public key since they are password auth) other than KeeAgent sending a blast of keys to PuTTY? I'm assuming KeeAgent should only respond if PuTTY receives a public key?

Any thoughts?

**Comment by dlech** [comment]
The way the SSH protocol works is...

* server asks for list of all public keys
* agent sends all loaded public keys
* server sends signing request if it has a matching public key
* agent sends signs the request and sends it back

They only way you can prevent SSH from sending all of the keys is to configure an identity file so that only one key is used or use a new feature in KeeAgent 0.9.x that allows you to select which key(s) to send.

Another work around might be to lock KeeAgent (different from locking KeePass) when you want to connect to the password only hosts.

**Comment by poblabs** [comment]
I see. I had it backwards - thanks for correcting me. I'll give the 0.9 beta a try and see how it goes.

**Comment by poblabs** [comment]
This may be a silly question but if you're able to prompt which key to send, are you able to add a hostname feature to send only that key to the hostname? Sort of like a way to auto-select the key? Not sure if that's how it works, and I'm sure you've been asked this before. 

Just a shame that > 5 keys makes things more difficult.
