### ISSUE TITLE
Emulated Pageant not accessible for WinSCP / PuTTY

### ISSUE THREAD

**Issue by kamikatze13** [dlech/KeeAgent#206]
Possibly related to #193 

Stumbled across this plugin and gave it a shot, since I'm using Pageant and KeePass already.

After setup of the key in Keepass / KeeAgent, both WinSCP as well as PuTTY fail with "No supported auth methods available (server sent: publickey)", as if Pageant wasn't running. Key is loaded in KeeAgent, however.

Starting Pageant while KeePass is open to add the key fails with "The already running Pageant refused to add the key". So Pageant _is_ running, after all?

Closing KeePass and running Pageant with the same key works fine.

KeeAgent 0.8.1.0
KeePass 2.37
WinSCP 5.9.6
Putty 0.65
Windows 1709 Build 16299.64

**Comment by markschuh** [comment]
Setup works perfect for me - but with newer tool versions (execpt KeePass)

My ideas to narrow down the root cause:

Both KeePass (with KeeAgent) and PuTTY/WinSCP run under the same user - right?

What type of key have you used? Test again with a RSA 2048bit key to avoid key type caused issues.

Have you noticed, your Putty and WinSCP versions are quite outdated? I suggest you update and try again. Also the KeeAgent Beta (0.9.1.0) is worth a quick try, if an upgrade solves your problem.  But to be true, I doubt your problem is caused by outdated version - AFAIK not much had happend in the Pageant communication over time.

Additionally you might play with "Client" vs "Agent" mode of KeeAgent. Of course "Agent" and full replacement of pageant by KeeAgent is the final target - but testing the different possible combinations may help to narrow down the root cause of the issue in your installation or potentially identify a workaround setup. Compare  https://lechnology.com/software/keeagent/usage/options-and-settings/

**Comment by kamikatze13** [comment]
Thanks for your reply, i finally managed to find time to try and fix the issue.

the problem was the key length: i went a little overboard with 4096b - 2048b worked first try.

**Comment by kamikatze13** [comment]
addendum: it worked only once for some reason.

since you mentioned whether the applications run under the same user, i tried to run keepass/putty/winscp elevated - one at a time as well as all of them.

both winscp as well as putty can _reliably_ authenticate with keeagent if they run _elevated_/as admin, even the 4096b key works. i am fairly sure keepass is not run as admin, though.

also, i should add, i updated all of the software mentioned to their newest stable versions:
winscp 5.13.1
putty 0.70
keepass 2.38
keeagent 0.10.1
windows 1709 build 16299.371
