### ISSUE TITLE
Compatibility with the Win10 1709 ssh client

### ISSUE THREAD

**Issue by u1735067** [dlech/KeeAgent#207]
Hello, 

Windows can now provide a "native" ssh client, it also provides a ssh-agent service, but I don't like it and prefer to see it disabled, I'd rather use KeeAgent, like for PuTTY :) .

I've player a bit with this new ssh client, and I couldn't make it work with KeeAgent.
I've tried to set a socket file `c:\tmp\ssh-agent.socket` and setting the env with `set SSH_AUTH_SOCK=C:\Tmp\ssh-agent.socket` (or even `set SSH_AUTH_SOCK=C:\\Tmp\\ssh-agent.socket`), but after comparing the verbose logs, here's the result: 
```
debug3: socket:0, socktype:1, io:00000161602505A0, fd:4
debug1: pubkey_prepare: ssh_fetch_identitylist: invalid format
debug3: close - io:00000161602505A0, type:2, fd:4, table_index:4
```
This is with both Cygwin and msysGit formats (by matching the content of the file, which looks like an address, I guess ssh would expect the real content, not an address, and there was no way this could work :) )

With default env and the ssh-agent disabled: 
```
debug3: socket:0, socktype:1, io:00000164A016C6B0, fd:4
debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
debug3: close - io:00000164A016C6B0, type:2, fd:4, table_index:4
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
```

And with default env & ssh-agent started (but no key): 
```
debug3: socket:0, socktype:1, io:000001EDCC23FAA0, fd:4
debug3: close - io:000001EDCC23FAA0, type:2, fd:4, table_index:4
```

Could KeeAgent provide a (Named?)Pipe at \\\\.\pipe\openssh-ssh-agent with the expected content (like on Mac/Linux?) ? With this Pipe enabled via configuration I guess.

Anyway, thanks for KeeAgent :)

**Comment by Alex131089** [comment]
I saw https://github.com/vuori/weasel-pageant, but this seems to rely on WSL and this ssh client doesn't seems to rely on WSL (at least I don't have it enabled).

**Comment by dlech** [comment]
Do you have a link for this "native" client?

**Comment by Alex131089** [comment]
https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/
I can probably upload ssh.exe if needed.

**Comment by dlech** [comment]
Thanks. No need to upload, I should be able to figure it out from the blog post.

**Comment by dlech** [comment]
This is basically implemented. The OpenSSH version shipping with Windows seems to be broken at this point, but it works with https://github.com/PowerShell/openssh-portable (at commit 8906783) that I compiled myself.

I need to do some more research on how to make it more secure, for example, by limiting clients to only processes with the same SID as the current user. Also, I imagine Microsoft will change things around until it is out of beta, so well have to keep an eye on their changes.

**Comment by dlech** [comment]
You can test, but expect problems: https://lechnology.com/2017/12/keeagent-beta-0-9-2-released/

**Comment by Alex131089** [comment]
As expected (I suppose that's what you're talking about), after enabling the feature and without setting `SSH_AUTH_SOCK`: 
```
debug3: socket:0, socktype:1, io:0000026CEC54ECC0, fd:4
debug1: pubkey_prepare: ssh_fetch_identitylist: invalid format
debug3: close - io:0000026CEC54ECC0, type:2, fd:4, table_index:4
```
I'll test again when they release a new version.
Thanks :)

**Comment by dlech** [comment]
Yes, I saw the same "invalid format" error when running `ssh-add -l`.

**Comment by jhit** [comment]
@dlech I think in Win10 Microsoft uses this codebase: https://github.com/PowerShell/Win32-OpenSSH
not the outdated repo you mentioned (https://github.com/PowerShell/openssh-portable)
Did you try Win32-OpenSSH with KeeAgent too?

**Comment by jhit** [comment]
@dlech Thanks, Daniel. I was misled by the more recent releases in the Win32-OpenSSH repository.

**Comment by markschuh** [comment]
I assume the "invalid format" is caused by Win32-OpenSSH using "Microsoft CNG" - what will be replaced by LibreSSL, See the related comment in the [Win32-OpenSSH Project Status](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status) and result of my tests below.

The following has worked for me now:
  KeeAgent Beta 0.9.2  /  KeePass 2.37 / Windows 10 - 1709 
  with option "Enable agent for Windows OpenSSH (experimental)"  enabled 
  and running in "Agent mode":

a) while using the Windows Feature "OpenSSH Client (Beta)" - which is:
   C:\Windows\System32\OpenSSH\ssh -V
   OpenSSH_7.5p1, without OpenSSL
In this setup I can only use keys of type "ssh-ed25519". All other types seem to run into "invalid format". But this also happens when KeeAgent is stopped and original "ssh-agent" started.

b) while using a newer Win32-OpenSSH - installed via "The Universal OpenSSH Installer" at https://github.com/DarwinJS/ChocoPackages/tree/master/openssh
  C:\>"C:\Program Files\OpenSSH-Win64\ssh.exe" -V
  OpenSSH_7.6p1, LibreSSL 2.5.3
In this setup other key types work, too  (tested with "ssh-rsa" with 2048bit and "ecdsa-sha2-nistp256")

Using KeeAgent Beta 0.9.2 in Client mode - with service "ssh-agent"  (aka "C:\WINDOWS\System32\openssh\ssh-agent.exe") running - does not work.

**Comment by dlech** [comment]
Thanks for the update. Glad to hear it is working with the official Windows software. Client mode is not fully implemented yet, so it is not surprising that it is not working.

**Comment by DimeOne** [comment]
I've been able to test KeeAgent Beta 0.9.2 with Windows 10 OpenSSH Beta Client and WSL.

OpenSSH_7.5p1, without OpenSSL
Ubuntu 16.04 WSL with OpenSSH

For OpenSSH Beta Client I enabled "Enable agent for Windows OpenSSH (experimental)" but kept getting an error stating ```error fetching identities: invalid format``` when using ```ssh-add -l```

I imported a new generated key using ED25519 instead of rsa and loaded it into the Keepass Agent which worked and ```ssh-add -l``` started showing identities.

As soon as I add another non ED25519 key to the agent, I am receiving ```error fetching identities: invalid format``` again when calling ```ssh-add -l```.

It would be nice to have an option to only forward ED25519 to OpenSSH client as long as it doesn't support RSA keys to allow simultanious usage of WSL with RSA support and OpenSSH.

In my case, some remotes do not allow ED25519 or do not have this key installed yet and I have to switch to the WSL to use RSA keys. For now this means loading and unloading the RSA keys manually.

**Comment by strarsis** [comment]
Currently working howto: https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49

**Comment by DimeOne** [comment]
Doesn't this howto require bash to be running when using ssh?
I thought the new OpenSSH client would not have to start a bash before launching ssh, so I am confused how this howto is supposed to work. I am running ssh.exe from a PowerShell mostly.

**Comment by strarsis** [comment]
@DimeOne: Yes, this howto is for *nix and WSL/Bash on Windows shells.
In your case `SSH_AUTH_SOCK` has to be set as (Windows) environment variable to the KeeAgent socket file.

**Comment by markschuh** [comment]
Win10 1803 ssh  (current Insider build nr 17133.13) uses now LibreSSL
   C:\>"%SystemRoot%\system32\OpenSSH\ssh" -V
   OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4

Use of KeeAgent with this ssh works well for me even with RSA keys, I have used the latest KeeAgent v0.10.1, and the - still experimental - flag for OpenSSH is activated inside KeeAgent global options.

There remains only one nuisance for me: Deactivation of the flag does not stop KeeAgent to provide the "openssh-ssh-agent" pipe. An error message "Windows OpensSSH agent is already running." pops up during each close of KeeAgent Global Options dialogue after first activation. But it is KeeAgent itself, which does not stop using the pipe, when instructed to do. I assume, this may be caused by "listeningServer = null;" in line 72 of SshAgentLib/WindowsOpenSshPipe.cs, while stop also references to this variable.

IMHO Use of ssh within WSL is a complete different setup  - not to mix up with this issue.

**Comment by Geobert** [comment]
Hi there,

I'm trying to use the "native" openssh client of Win 10 with KeeAgent and I encounter this "windows openssh agent is already running".

How do I turn off windows openssh agent in order to use KeeAgent instead?

**Comment by Alex131089** [comment]
On Win10 1709, it is provided by a service named `ssh-agent`, you can check in `services.msc` : 
![image](https://user-images.githubusercontent.com/1735067/69007469-60825d00-093e-11ea-88d7-b15b24137f45.png)

**Comment by Geobert** [comment]
Mine is disabled as well:
![image](https://user-images.githubusercontent.com/72570/69009100-39318d00-094a-11ea-938f-4f79e8d427d0.png)

But I still have this error :-/

**Comment by strarsis** [comment]
This Howto may be helpful: https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49

**Comment by rdoering** [comment]
This issue isn't solved with new ssh version OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2 shipped by Microsoft.

**Comment by dlech** [comment]
This is working for me on WIndows 11. Please open a new issue with detailed steps on how to reproduce the problem if it is not working for you.

**Comment by i3v** [comment]
Works OK for me in Windows 10: in cmd, powershell (`ssh -V` : `OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2`), git bash, cygwin.
Most readable manual is [this](https://www.endpointdev.com/blog/2022/08/keeagent-with-git-bash-and-windows-cli-openssh/).

**Comment by strarsis** [comment]
@i3v: Does it also work for you with WSL 2 (or WSL 1)?

**Comment by i3v** [comment]
@strarsis , personally I've not tried to integrate KeeAgent with WSL2 yet - I had no real use cases to do that. 
There seem to be at least two approaches suggested in #339:
 * the [official](https://github.com/dlech/KeeAgent/blob/431b32a63436e4e8813036aeec41cbd7b4168233/doc/usage/tips-and-tricks.rst#windows-subsystem-for-linux-wsl) "use ssh from Windows" approach. 
 * [wsl-ssh-agent+npiperelay.exe](https://gist.github.com/strarsis/e533f4bca5ae158481bbe53185848d49)
