### ISSUE TITLE
VSCode Intigration

### ISSUE THREAD

**Issue by scj643** [dlech/KeeAgent#241]
I have been wanting to use this with git bash and VSCode. Currently the only way to get it to work is to have git bash launch VSCode which is not optimal.

**Comment by mendhak** [comment]
You need to set the Windows environment variable for `SSH_AUTH_SOCK`.  Example:

![image](https://user-images.githubusercontent.com/746276/42528978-19b4ff30-8475-11e8-8a2d-a66de877787a.png)


This is because VSCode directly invokes `git.exe` and any env vars you may have set as part of your git bash don't get picked up.

**Comment by musm** [comment]
Thanks @mendhak fixed it for me! Now my only issue is WSL2...

**Comment by musm** [comment]
Actually setting the env variable end up breaking KeeAgent when using `ssh` from the shell etc. No idea why setting the env variable for `SSH_AUTH_SOCK` breaks KeeAgent.

**Comment by ezekielnewren** [comment]
My answer in #242  goes into a little more detail of how to set this up and makes it work generically even for systems with multiple concurrent users.

**Comment by dlech** [comment]
VS Code also has options to set the environment for a terminal.
